#!/bin/sh

set -e
umask 0002

OPTIONS="--remove name --hostname name"

if [ "$1" == "--" ]; then

  /usr/libexec/device-set ${OPTIONS} "$@"

  if systemctl is-active --quiet mlmmj-autodiscovery.service; then
    /usr/bin/sudo /usr/bin/systemctl try-reload-or-restart mlmmj-autodiscovery.service
  else
    echo "list will be removed on next reboot."
  fi

elif [ "$1" == "-c" ]; then

  /usr/libexec/device-set ${OPTIONS} "$@"

fi

